// system.debug('Ahm And');


/*
string model ='flu';
system.debug(model);

string brand='reno';
system.debug(brand);

string color ='grey';
system.debug(color);

string mycar = brand + '' + model + '' + color + '';
system.debug(mycar);

*/


/*
myAsSalesforce ms = new myAsSalesforce();
ms.myFirstCode();
*/

/*
myAsSalesforce ff = new myAsSalesforce();
ff.myFavorites();
*/
/*
MyCity cc = new MyCity();
 cc.cityInformation();

/*
MyCity dd = new MyCity();
dd.stringMethod();
*/

/*
List<string> gezegenler = new list<string>{'Dünya', 'Venüs', 'Mars', 'merkür', 'saturn', 'jupiter', 'dünya', 'mars'};
system.debug('Liste: ' + gezegenler);

Boolean bosmu = gezegenler.isEmpty();
System.debug('liste bos mu?:' + bosmu);

integer say = gezegenler.size();
System.debug('listede kac eleman var: ' + say);

*/
/*
MyCity trh = new MyCity();
trh.dateMethod();
*/

        
Account ac1 = new Account();
        ac1.Name = 'Summer Fest LLC';
        ac1.ParentId = '0018d00000GqQDdAAN';
        ac1.Type= 'Tecnology Partner';
        ac1.Rating='Hot';
        ac1.AnnualRevenue= 200000000;

        insert ac1;

        











